version: '3.9'

services:
  mongoDB_01:
    container_name: mongoDB_01
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
    volumes:
      - ./data_01/db:/data/db
      - ./data_01/configdb:/data/configdb
      - ./scripts:/scripts

  mongoDB_02:
    container_name: mongoDB_02
    image: mongo:4.4
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
    volumes:
      - ./data_02/db:/data/db
      - ./data_02/configdb:/data/configdb
    depends_on:
      - mongoDB_01

  mongoDB_03:
    container_name: mongoDB_03
    image: mongo:4.4
    restart: always
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
    volumes:
      - ./data_03/db:/data/db
      - ./data_03/configdb:/data/configdb
    depends_on:
      - mongoDB_01
